# Script mode (cmake -P), run by the build (src/CMakeLists.txt) whenever a pattern file changes:
#   cmake -DOUTPUT=<file.cpp> -DFILES=<a.rle|b.rle|...> -P EmbedPatterns.cmake
# Writes a C++ source that defines embeddedPatternFiles() (wxLife/core/EmbeddedFile.h): every file as a char
# array, so the program needs no data files next to it on any platform. Arrays, not string literals, because
# MSVC limits a string literal to 64 KiB. Pattern files must be ASCII; gzip files (.gz) may hold any byte, and
# their bytes from 0x80 up are written as character literals ('\x8b'), which fit a char whether it is signed or
# not, where 0x8b would not. FILES is separated by '|', since a ';' would split the argument on the command
# line.
if(NOT DEFINED OUTPUT OR NOT DEFINED FILES)
    message(FATAL_ERROR "EmbedPatterns.cmake requires -DOUTPUT=... and -DFILES=...")
endif()
string(REPLACE "|" ";" files "${FILES}")

string(REPEAT "0x..," 16 line)
set(arrays "")
set(entries "")
set(index 0)
foreach(file IN LISTS files)
    get_filename_component(name "${file}" NAME)
    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" digits)
    math(EXPR size "${digits} / 2")
    if(size EQUAL 0)
        message(FATAL_ERROR "${file} is empty")
    endif()
    # Pairs are matched from the start, so each "0x.." is one byte.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Sixteen bytes per line (CMake's regular expressions have no {n}).
    string(REGEX REPLACE "(${line})" "\\1\n    " bytes "${bytes}")
    if(name MATCHES "\\.gz$")
        string(REGEX REPLACE "0x([89a-f][0-9a-f])" "'\\\\x\\1'" bytes "${bytes}")
    elseif(bytes MATCHES "0x[89a-f]")
        message(FATAL_ERROR "${file} is not ASCII")
    endif()
    string(APPEND arrays "// ${name}\nconstexpr std::array<char, ${size}> kFile${index}{\n    ${bytes}};\n\n")
    set(array "kFile${index}")
    string(APPEND entries
           "        EmbeddedFile{.name = \"${name}\", .text = {${array}.data(), ${array}.size()}},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(CONFIGURE OUTPUT "${OUTPUT}.new" @ONLY CONTENT [[
// Generated by cmake/EmbedPatterns.cmake from the files in patterns/. Do not edit.
#include <array>
#include <span>
#include <string_view>

#include "wxLife/core/EmbeddedFile.h"

namespace wxLife::core
{

namespace
{

@arrays@}  // namespace

std::span<const EmbeddedFile> embeddedPatternFiles() noexcept
{
    static constexpr std::array kFiles{
@entries@    };
    return kFiles;
}

}  // namespace wxLife::core
]])
# Replacing an identical file would only rebuild it again.
file(COPY_FILE "${OUTPUT}.new" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.new")
